# === Nixpacks Configuration ===

providers = ["node", "python"]

[phases.setup]
aptPkgs = [
    "libnss3", "libnspr4", "libdbus-1-3", "libatk1.0-0", "libatk-bridge2.0-0",
    "libcups2", "libdrm2", "libatspi2.0-0", "libxcomposite1", "libxdamage1",
    "libxfixes3", "libxrandr2", "libgbm1", "libpango-1.0-0", "libcairo2",
    "libx11-xcb1", "libfontconfig1"
]

[phases.install]
cmds = ["npm run install-all"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
startCmd = "npm start"