# === Nixpacks Configuration ===

providers = ["node", "python", "chromium-with-fonts"]

[phases.install]
cmds = ["npm run install-all"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
startCmd = "npm start"